# -*- coding: utf-8 -*-
"""
Bank soal UAS E-Business (Pertemuan 10-15).
Sumber materi: Bahan Ajar E-Business Pertemuan 10-15, Ardiansyah Japlani, S.E., M.B.A.
Konsentrasi Bisnis, FEB Universitas Muhammadiyah Metro.

Total 250 soal. Setiap mahasiswa mendapatkan 20 soal acak dari bank ini,
diseleksi dan diacak berdasarkan NPM (lihat app.py fungsi ambil_soal_uas).

Format tiap soal: {"q": pertanyaan, "o": [opsi A, B, C, D], "a": indeks_jawaban_benar}
Indeks jawaban: 0 = A, 1 = B, 2 = C, 3 = D (posisi opsi akan diacak lagi saat ujian).
"""

# ================== KONFIGURASI UAS ==================
DURASI_UAS_MENIT = 7          # maksimal waktu pengerjaan (menit), tanpa waktu tambahan
JUMLAH_SOAL_PER_MAHASISWA = 20  # jumlah soal acak yang diterima tiap mahasiswa
JUMLAH_MAHASISWA = 44
ACAK_OPSI = True              # opsi jawaban diacak ulang per NPM

# ================== BANK SOAL (250) ==================
UAS_BANK = [
    # ---------- Pertemuan 10: Keamanan Siber dan Privasi Data (1-50) ----------
    {"q": "Triad CIA dalam keamanan informasi terdiri dari...", "o": ["Kerahasiaan, Integritas, Ketersediaan", "Kecepatan, Integrasi, Akurasi", "Kontrol, Investasi, Audit", "Koneksi, Identitas, Akses"], "a": 0},
    {"q": "Dimensi triad CIA yang memastikan hanya pihak berwenang dapat mengakses data adalah...", "o": ["Kerahasiaan", "Integritas", "Ketersediaan", "Otentikasi"], "a": 0},
    {"q": "Dimensi triad CIA yang memastikan data tidak diubah secara tidak sah adalah...", "o": ["Integritas", "Kerahasiaan", "Ketersediaan", "Akuntabilitas"], "a": 0},
    {"q": "Dimensi triad CIA yang memastikan layanan dapat diakses saat dibutuhkan adalah...", "o": ["Ketersediaan", "Kerahasiaan", "Integritas", "Validitas"], "a": 0},
    {"q": "Contoh penerapan kerahasiaan pada e-business adalah...", "o": ["Enkripsi data kartu dan kontrol akses berbasis peran", "Penyeimbang beban dan pencadangan", "Tanda tangan digital dan jejak audit", "Mitigasi DDoS"], "a": 0},
    {"q": "Contoh penerapan integritas data pada e-business adalah...", "o": ["Tanda tangan digital dan jejak audit transaksi", "Enkripsi kartu pembayaran", "Penyeimbang beban", "Firewall jaringan"], "a": 0},
    {"q": "Contoh penerapan ketersediaan pada e-business adalah...", "o": ["Penyeimbang beban, pencadangan, dan mitigasi DDoS", "Kontrol akses berbasis peran", "Tanda tangan digital", "Enkripsi data"], "a": 0},
    {"q": "Serangan siber yang memanfaatkan psikologi manusia, bukan kelemahan teknis, adalah...", "o": ["Phishing dan rekayasa sosial", "Injeksi SQL", "DDoS", "Ransomware"], "a": 0},
    {"q": "Perangkat lunak jahat yang mengenkripsi data lalu menuntut tebusan disebut...", "o": ["Ransomware", "Phishing", "Adware", "Spyware biasa"], "a": 0},
    {"q": "Serangan yang membanjiri server dengan permintaan palsu hingga layanan lumpuh disebut...", "o": ["DDoS", "SQL injection", "Man in the middle", "Brute force"], "a": 0},
    {"q": "Injeksi SQL berhasil dilakukan penyerang terutama karena...", "o": ["Kolom input tidak divalidasi", "Kata sandi terlalu panjang", "Server terlalu cepat", "Data dienkripsi ganda"], "a": 0},
    {"q": "Pertahanan utama menghadapi phishing adalah...", "o": ["Pelatihan kesadaran keamanan pengguna", "Menambah kapasitas server", "Mematikan enkripsi", "Memperbanyak iklan"], "a": 0},
    {"q": "Model ransomware terkini menambahkan ancaman ganda berupa...", "o": ["Membocorkan data jika tebusan tidak dibayar", "Menggandakan kecepatan server", "Menghapus iklan", "Memperbaiki data otomatis"], "a": 0},
    {"q": "Serangan DDoS sering digunakan sebagai...", "o": ["Pengalih perhatian dari serangan lain", "Cara mempercepat transaksi", "Metode pencadangan", "Alat pemasaran"], "a": 0},
    {"q": "Ancaman dari dalam (insider threat) paling efektif dikurangi dengan...", "o": ["Prinsip hak akses minimum dan pemantauan aktivitas", "Menambah bandwidth", "Menghapus semua audit", "Memberi semua karyawan akses penuh"], "a": 0},
    {"q": "Serangan rantai pasok perangkat lunak terjadi ketika penyerang...", "o": ["Menyusupkan kode jahat melalui pustaka atau pemasok tepercaya", "Membanjiri server dengan trafik", "Menebak kata sandi", "Mencuri perangkat keras"], "a": 0},
    {"q": "Prinsip pertahanan berlapis (defense in depth) berarti...", "o": ["Menumpuk beberapa kontrol agar kegagalan satu lapis tidak membuka seluruh sistem", "Mengandalkan satu firewall tunggal", "Meniadakan pelatihan karyawan", "Menyimpan seluruh data tanpa enkripsi"], "a": 0},
    {"q": "Prinsip inti pendekatan zero trust adalah...", "o": ["Jangan pernah percaya, selalu verifikasi", "Percaya semua pihak internal", "Verifikasi hanya di awal", "Buka akses tanpa syarat"], "a": 0},
    {"q": "Zero trust relevan saat ini terutama karena...", "o": ["Karyawan bekerja dari banyak lokasi dan layanan berjalan di komputasi awan", "Semua orang bekerja di satu ruangan", "Internet sudah tidak dipakai", "Data tidak lagi berharga"], "a": 0},
    {"q": "Perbedaan mendasar keamanan dan privasi adalah...", "o": ["Keamanan melindungi dari akses tidak sah, privasi mengatur cara pengumpulan dan penggunaan data yang sah", "Keduanya sama persis", "Privasi hanya soal enkripsi", "Keamanan hanya soal izin pengguna"], "a": 0},
    {"q": "Regulasi Indonesia yang khusus melindungi data pribadi adalah...", "o": ["UU PDP No. 27 Tahun 2022", "UU No. 20 Tahun 2008", "UU ITE No. 11 Tahun 2008 saja", "PP No. 7 Tahun 2021"], "a": 0},
    {"q": "GDPR Uni Eropa memberi ancaman denda hingga...", "o": ["4 persen omzet global tahunan", "1 persen laba bersih", "10 persen aset", "Rp2 miliar tetap"], "a": 0},
    {"q": "Hak untuk dilupakan dan portabilitas data merupakan ciri khas regulasi...", "o": ["GDPR", "PCI DSS", "PP UMKM", "PSAK"], "a": 0},
    {"q": "Standar teknis wajib bagi pedagang yang memproses data kartu pembayaran adalah...", "o": ["PCI DSS", "GDPR", "UU PDP", "ISO 9001"], "a": 0},
    {"q": "Regulasi Uni Eropa yang mengklasifikasi risiko sistem kecerdasan buatan adalah...", "o": ["AI Act", "GDPR", "PCI DSS", "UU PDP"], "a": 0},
    {"q": "Hak subjek data menurut UU PDP mencakup...", "o": ["Hak mengetahui, mengakses, memperbaiki, menghapus, dan menarik persetujuan", "Hak menggandakan server", "Hak menaikkan harga", "Hak menolak pajak"], "a": 0},
    {"q": "Prinsip privasi sejak perancangan (privacy by design) menuntut perusahaan...", "o": ["Menanamkan perlindungan privasi sejak tahap awal pengembangan", "Menambah privasi setelah produk gagal", "Mengumpulkan data sebanyak mungkin", "Mengabaikan persetujuan"], "a": 0},
    {"q": "Sesuai prinsip minimalisasi data, perusahaan sebaiknya...", "o": ["Mengumpulkan data seperlunya dan menghapus bila tidak diperlukan", "Menyimpan semua data selamanya", "Menjual data ke pihak ketiga", "Menyalin data tanpa batas"], "a": 0},
    {"q": "Tahapan daur hidup data yang benar adalah...", "o": ["Pengumpulan, penyimpanan, penggunaan, pembagian, pemusnahan", "Penjualan, pembelian, pengembalian", "Iklan, promosi, diskon", "Login, logout, hapus akun"], "a": 0},
    {"q": "Siklus manajemen risiko keamanan berjalan sebagai...", "o": ["Proses berulang: identifikasi, nilai, terapkan kontrol, pantau, perbaiki", "Kegiatan satu kali di awal", "Tugas tahunan tanpa tindak lanjut", "Urusan pemasaran"], "a": 0},
    {"q": "Empat tahap umum siklus tanggap insiden adalah...", "o": ["Persiapan; deteksi dan analisis; penanggulangan, pemberantasan, pemulihan; pembelajaran pascainsiden", "Iklan, jual, kirim, tagih", "Login, akses, unduh, hapus", "Rencana, doa, tunggu, lupakan"], "a": 0},
    {"q": "Autentikasi berlapis (MFA) berguna untuk...", "o": ["Memperkuat akses sistem penting dengan lebih dari satu faktor", "Mempercepat pemuatan halaman", "Menurunkan biaya server", "Menggantikan pencadangan"], "a": 0},
    {"q": "Enkripsi sebaiknya diterapkan pada data...", "o": ["Saat disimpan dan saat dikirim", "Hanya saat dicetak", "Hanya di akhir tahun", "Tidak perlu sama sekali"], "a": 0},
    {"q": "Pencadangan (backup) yang baik untuk melawan ransomware sebaiknya...", "o": ["Terpisah dari jaringan utama dan diuji pemulihannya", "Disimpan di server yang sama", "Tidak pernah diuji", "Hanya di email pribadi"], "a": 0},
    {"q": "Biaya terbesar dari sebuah insiden kebocoran data umumnya berasal dari...", "o": ["Hilangnya pelanggan dan kepercayaan", "Pembelian kabel baru", "Biaya listrik", "Iklan tambahan"], "a": 0},
    {"q": "Alasan pencegahan lebih dipilih daripada pemulihan adalah...", "o": ["Pencegahan jauh lebih murah daripada pemulihan", "Pemulihan selalu gratis", "Pencegahan tidak berguna", "Regulator melarang pencegahan"], "a": 0},
    {"q": "Yang dimaksud permukaan serangan (attack surface) adalah...", "o": ["Seluruh titik yang dapat dimasuki penyerang", "Jumlah karyawan", "Luas kantor fisik", "Ukuran layar server"], "a": 0},
    {"q": "Penyerang mengincar data pelanggan terutama karena...", "o": ["Data memiliki nilai ekonomi di pasar gelap", "Data tidak berguna", "Data mudah dihapus", "Data memperlambat server"], "a": 0},
    {"q": "QS yang menjadi landasan etika privasi data (larangan memata-matai) adalah...", "o": ["QS Al-Hujurat ayat 12", "QS Al-Maidah ayat 2", "QS Ali Imran ayat 159", "QS Az-Zumar ayat 18"], "a": 0},
    {"q": "Prinsip menjaga data pelanggan sebagai amanah paling dekat dengan nilai profetik...", "o": ["Amanah", "Tabligh", "Fathonah", "Riya"], "a": 0},
    {"q": "Perusahaan bisa saja aman secara teknis tetapi tetap melanggar privasi apabila...", "o": ["Menyalahgunakan data yang dikumpulkan secara sah", "Menggunakan enkripsi kuat", "Melatih karyawan", "Mencadangkan data"], "a": 0},
    {"q": "Kepatuhan terhadap regulasi privasi sebaiknya dipandang sebagai...", "o": ["Pembeda kompetitif yang memperkuat kepercayaan", "Beban tanpa manfaat", "Hal opsional", "Urusan teknis semata"], "a": 0},
    {"q": "Kontrol akses berbasis peran (role based access) bertujuan...", "o": ["Membatasi akses sesuai peran dan kebutuhan pengguna", "Membuka semua data untuk semua orang", "Menghapus kata sandi", "Mematikan audit"], "a": 0},
    {"q": "Pelajaran utama dari kasus kebocoran data lintas platform di Indonesia adalah...", "o": ["Berinvestasi pada keamanan sejak awal dan komunikasi krisis yang jujur", "Menyembunyikan insiden dari publik", "Mengabaikan UU PDP", "Menghapus seluruh pelanggan"], "a": 0},
    {"q": "Denda besar GDPR kepada perusahaan teknologi global menegaskan bahwa...", "o": ["Kepatuhan privasi adalah risiko finansial nyata", "Privasi hanya formalitas", "Denda tidak pernah ditagih", "Regulasi mudah diabaikan"], "a": 0},
    {"q": "Keamanan siber sebaiknya ditempatkan sebagai...", "o": ["Bagian inti strategi bisnis", "Urusan teknis departemen TI semata", "Kegiatan sekali setahun", "Tanggung jawab pelanggan"], "a": 0},
    {"q": "Ketiga dimensi triad CIA sering...", "o": ["Saling bertukar sehingga perlu titik keseimbangan", "Selalu berjalan otomatis sempurna", "Tidak berhubungan sama sekali", "Hanya berlaku untuk bank"], "a": 0},
    {"q": "Penguncian sistem yang berlebihan cenderung...", "o": ["Meningkatkan kerahasiaan tetapi menurunkan ketersediaan dan kenyamanan", "Meningkatkan semua dimensi sekaligus tanpa biaya", "Tidak berpengaruh apa pun", "Menghapus kebutuhan enkripsi"], "a": 0},
    {"q": "Langkah awal program keamanan yang sehat adalah...", "o": ["Mengidentifikasi aset data dan mengklasifikasi tingkat sensitivitasnya", "Langsung membeli server termahal", "Mengabaikan pelatihan", "Menonaktifkan firewall"], "a": 0},
    {"q": "Pejabat pelindungan data (DPO) menurut UU PDP berperan...", "o": ["Mengawasi kepatuhan pelindungan data dan pelaporan kebocoran", "Mengatur harga produk", "Merekrut karyawan", "Menyusun iklan"], "a": 0},

    # ---------- Pertemuan 11: Keberlanjutan dan Etika Bisnis Digital (51-100) ----------
    {"q": "Konsep triple bottom line menilai kinerja perusahaan pada tiga lini yaitu...", "o": ["Keuntungan, manusia, dan planet", "Modal, utang, laba", "Produk, harga, tempat", "Iklan, promosi, diskon"], "a": 0},
    {"q": "ESG merupakan singkatan dari...", "o": ["Environmental, Social, Governance", "Economy, Sales, Growth", "Energy, Security, Global", "Ethics, Society, Green"], "a": 0},
    {"q": "Contoh dimensi Environmental pada bisnis digital adalah...", "o": ["Pusat data hemat energi dan kemasan ramah lingkungan", "Struktur dewan yang sehat", "Perlindungan pekerja gig", "Kebijakan antikorupsi"], "a": 0},
    {"q": "Contoh dimensi Social pada bisnis digital adalah...", "o": ["Perlindungan pekerja gig dan inklusi keuangan", "Pusat data hemat energi", "Transparansi laporan keuangan", "Kemasan daur ulang"], "a": 0},
    {"q": "Contoh dimensi Governance pada bisnis digital adalah...", "o": ["Transparansi data, antikorupsi, dan struktur dewan yang sehat", "Jejak karbon pengiriman", "Literasi digital", "Energi terbarukan gudang"], "a": 0},
    {"q": "Investor menggunakan skor ESG terutama untuk...", "o": ["Menilai risiko jangka panjang perusahaan", "Menentukan warna logo", "Mengatur jam kerja", "Memilih menu kantin"], "a": 0},
    {"q": "Tiga sumber utama jejak karbon bisnis digital adalah...", "o": ["Pusat data, logistik pengiriman, dan limbah elektronik", "Kertas, tinta, dan amplop", "Iklan, promosi, dan diskon", "Gaji, sewa, dan pajak"], "a": 0},
    {"q": "Anggapan bahwa bisnis digital selalu ramah lingkungan bersifat...", "o": ["Tidak sepenuhnya benar karena tetap ada jejak karbon", "Sepenuhnya benar tanpa syarat", "Tidak pernah dibahas", "Hanya berlaku di Eropa"], "a": 0},
    {"q": "Pusat data menghasilkan jejak karbon karena...", "o": ["Mengonsumsi listrik besar untuk komputasi dan pendinginan", "Menggunakan banyak kertas", "Mencetak struk", "Mengirim surat pos"], "a": 0},
    {"q": "Emisi logistik terbesar biasanya muncul pada...", "o": ["Tahap pengiriman akhir menuju rumah pelanggan", "Tahap desain produk", "Tahap iklan", "Tahap pembuatan logo"], "a": 0},
    {"q": "Limbah elektronik menjadi masalah lingkungan karena...", "o": ["Sulit terurai dan mengandung bahan berbahaya", "Mudah didaur ulang tanpa biaya", "Tidak berdampak apa pun", "Selalu bernilai tinggi"], "a": 0},
    {"q": "Model ekonomi sirkular menggantikan pola...", "o": ["Ambil, pakai, buang", "Beli, jual, untung", "Rencana, ukur, belajar", "Login, akses, keluar"], "a": 0},
    {"q": "Contoh praktik ekonomi sirkular adalah...", "o": ["Program tukar tambah, perbaikan, dan daur ulang", "Membakar barang bekas", "Menimbun stok tak terpakai", "Menaikkan harga pengiriman"], "a": 0},
    {"q": "Desain antarmuka yang menjebak pengguna mengambil keputusan yang tidak dikehendaki disebut...", "o": ["Pola gelap (dark pattern)", "Pola terang", "Antarmuka adaptif", "Desain responsif"], "a": 0},
    {"q": "Contoh pola gelap adalah...", "o": ["Langganan yang sulit dibatalkan atau biaya tersembunyi di langkah akhir", "Tombol batal yang jelas", "Harga transparan", "Kebijakan privasi ringkas"], "a": 0},
    {"q": "Bias algoritma dapat muncul apabila sistem...", "o": ["Dilatih dengan data yang bias", "Diaudit secara berkala", "Menggunakan data seimbang", "Transparan kepada publik"], "a": 0},
    {"q": "Cara mengurangi bias algoritma adalah...", "o": ["Mengaudit algoritma secara berkala", "Menyembunyikan proses", "Menambah data bias", "Menghapus pengawasan"], "a": 0},
    {"q": "Klaim ramah lingkungan yang berlebihan atau tanpa bukti disebut...", "o": ["Greenwashing", "Green e-commerce", "Ekonomi sirkular", "Triple bottom line"], "a": 0},
    {"q": "Transparansi harga menuntut perusahaan...", "o": ["Menampilkan harga dan biaya tambahan secara jujur", "Menyembunyikan biaya di akhir", "Menaikkan harga diam-diam", "Mengubah harga tiap klik"], "a": 0},
    {"q": "Penggerak utama tren keberlanjutan menurut materi adalah...", "o": ["Generasi muda yang memilih merek sesuai nilai", "Regulator pajak", "Pemasok kertas", "Perusahaan logistik"], "a": 0},
    {"q": "Perusahaan yang mengabaikan keberlanjutan berisiko...", "o": ["Kehilangan pelanggan, talenta, dan akses pendanaan ESG", "Mendapat lebih banyak pelanggan", "Menurunkan biaya tanpa dampak", "Bebas dari regulasi"], "a": 0},
    {"q": "Praktik green e-commerce yang menekan emisi pengiriman adalah...", "o": ["Optimasi rute dan opsi pengiriman lambat yang menggabungkan paket", "Pengiriman kilat semua pesanan", "Kemasan berlapis plastik", "Pengembalian gratis tanpa batas"], "a": 0},
    {"q": "Green e-commerce dipandang menguntungkan karena...", "o": ["Menghemat biaya operasi sekaligus menarik konsumen peduli lingkungan", "Selalu menaikkan biaya tanpa manfaat", "Menghapus kebutuhan gudang", "Mengurangi jumlah pelanggan"], "a": 0},
    {"q": "Standar pelaporan keberlanjutan yang konsisten memungkinkan investor...", "o": ["Membandingkan perusahaan secara setara dan mengurangi klaim menyesatkan", "Menyembunyikan kinerja", "Menaikkan harga saham otomatis", "Menghindari pajak"], "a": 0},
    {"q": "QS yang menjadi dasar prinsip keberlanjutan (larangan berbuat kerusakan di bumi) adalah...", "o": ["QS Al-A'raf ayat 85", "QS Al-Hujurat ayat 12", "QS Al-Maidah ayat 2", "QS Ali Imran ayat 159"], "a": 0},
    {"q": "Prinsip pemeliharaan kemaslahatan dalam Islam yang sejalan dengan keberlanjutan disebut...", "o": ["Maqashid syariah", "Riba", "Gharar", "Maysir"], "a": 0},
    {"q": "Regulator di berbagai negara mulai menindak pola gelap karena...", "o": ["Desain manipulatif kini menjadi risiko hukum", "Pola gelap menaikkan pajak", "Pola gelap membantu konsumen", "Pola gelap wajib digunakan"], "a": 0},
    {"q": "Komitmen netral karbon platform global menunjukkan bahwa...", "o": ["Keberlanjutan dapat berjalan seiring efisiensi biaya energi", "Keberlanjutan selalu merugikan", "Energi terbarukan tidak mungkin", "Citra merek tidak penting"], "a": 0},
    {"q": "Perusahaan tidak lagi mengukur keberhasilan semata dari...", "o": ["Laba finansial", "Dampak lingkungan", "Tanggung jawab sosial", "Tata kelola"], "a": 0},
    {"q": "Kerangka ESG menerjemahkan tanggung jawab perusahaan menjadi...", "o": ["Dimensi yang dapat diukur dan dilaporkan", "Slogan iklan", "Target penjualan harian", "Warna kemasan"], "a": 0},
    {"q": "Program tukar tambah dan penjualan barang bekas tersertifikasi termasuk contoh...", "o": ["Ekonomi sirkular", "Greenwashing", "Pola gelap", "Bias algoritma"], "a": 0},
    {"q": "Manajer bertanggung jawab memastikan praktik bisnis digital...", "o": ["Tidak merugikan konsumen maupun masyarakat", "Selalu memaksimalkan data konsumen", "Menyembunyikan biaya", "Mengabaikan etika"], "a": 0},
    {"q": "Salah satu praktik green e-commerce pada pusat data adalah...", "o": ["Penggunaan energi terbarukan", "Menambah server tanpa batas", "Mematikan pencadangan", "Menghapus laporan"], "a": 0},
    {"q": "Pelaporan jejak karbon yang transparan kepada publik bertujuan...", "o": ["Membangun kepercayaan dan menghindari greenwashing", "Menyembunyikan emisi", "Menaikkan harga", "Mengurangi pelanggan"], "a": 0},
    {"q": "Yang membedakan multichannel dari omnichannel dalam konteks tanggung jawab data adalah...", "o": ["Bukan bagian bab keberlanjutan", "Tidak relevan", "Sama saja", "Tidak ada bedanya"], "a": 0},
    {"q": "Bias algoritma paling berisiko pada proses...", "o": ["Penilaian kredit dan penyaringan lamaran kerja", "Pemilihan warna tombol", "Penentuan jam operasional", "Desain logo"], "a": 0},
    {"q": "Pendanaan berbasis ESG mempertimbangkan...", "o": ["Kriteria lingkungan, sosial, dan tata kelola", "Hanya warna merek", "Hanya jumlah karyawan", "Hanya lokasi kantor"], "a": 0},
    {"q": "Etika bisnis digital pada intinya mengatur...", "o": ["Perilaku perusahaan dalam memanfaatkan teknologi dan data", "Tata letak gudang", "Warna seragam", "Menu kantin"], "a": 0},
    {"q": "Kemasan ramah lingkungan dan program pengembalian kemasan termasuk dimensi ESG...", "o": ["Environmental", "Social", "Governance", "Financial"], "a": 0},
    {"q": "Keberagaman tim dan literasi digital termasuk dimensi ESG...", "o": ["Social", "Environmental", "Governance", "Technical"], "a": 0},
    {"q": "Kebijakan privasi dan antikorupsi termasuk dimensi ESG...", "o": ["Governance", "Environmental", "Social", "Marketing"], "a": 0},
    {"q": "Perusahaan yang memadukan profitabilitas dengan tanggung jawab lingkungan dan sosial akan...", "o": ["Membangun reputasi dan loyalitas tahan lama", "Kehilangan seluruh laba", "Dilarang beroperasi", "Kehilangan investor"], "a": 0},
    {"q": "Tren konsumen muda bersedia membayar lebih untuk...", "o": ["Produk yang bertanggung jawab", "Produk paling murah selalu", "Produk tanpa merek", "Produk usang"], "a": 0},
    {"q": "Ekonomi sirkular membuka manfaat tambahan berupa...", "o": ["Aliran pendapatan baru dan perpanjangan siklus hidup produk", "Peningkatan limbah", "Kenaikan emisi", "Penurunan kualitas selalu"], "a": 0},
    {"q": "Sektor pusat data terhadap konsumsi listrik global cenderung...", "o": ["Terus meningkat", "Terus menurun tajam", "Selalu nol", "Tidak terukur"], "a": 0},
    {"q": "Perbedaan keberlanjutan dan sekadar pemasaran hijau ditentukan oleh...", "o": ["Adanya bukti nyata, bukan klaim berlebihan", "Ukuran font iklan", "Jumlah influencer", "Warna kemasan saja"], "a": 0},
    {"q": "Prinsip triple bottom line mendorong perusahaan menilai dampak terhadap...", "o": ["Manusia dan planet, bukan hanya profit", "Hanya pemegang saham", "Hanya pesaing", "Hanya regulator"], "a": 0},
    {"q": "Audit algoritma secara berkala termasuk praktik tata kelola untuk...", "o": ["Mencegah diskriminasi dan menjaga keadilan", "Menaikkan harga", "Menyembunyikan data", "Memperlambat sistem"], "a": 0},
    {"q": "Green e-commerce bukan sekadar tanggung jawab moral, melainkan juga...", "o": ["Cara menghemat biaya operasi", "Cara menaikkan emisi", "Beban tanpa manfaat", "Larangan regulasi"], "a": 0},
    {"q": "Perbaikan produk dan pembaruan barang bekas memperlihatkan penerapan...", "o": ["Ekonomi sirkular", "Pola gelap", "Bias algoritma", "Greenwashing"], "a": 0},

    # ---------- Pertemuan 12: AI Personalisasi dan Customer Experience (101-150) ----------
    {"q": "Personalisasi berbasis AI memungkinkan perusahaan...", "o": ["Menyajikan konten dan penawaran sesuai preferensi tiap individu", "Menyeragamkan semua pelanggan", "Menghapus data pelanggan", "Menaikkan harga acak"], "a": 0},
    {"q": "Pendekatan mesin rekomendasi yang menyarankan produk berdasarkan kemiripan perilaku antarpengguna adalah...", "o": ["Penyaringan kolaboratif", "Berbasis konten", "Hibrida", "Acak"], "a": 0},
    {"q": "Pendekatan mesin rekomendasi yang menyarankan produk mirip dengan yang disukai sebelumnya adalah...", "o": ["Berbasis konten", "Penyaringan kolaboratif", "Hibrida", "Segmentasi statis"], "a": 0},
    {"q": "Pendekatan yang menggabungkan penyaringan kolaboratif dan berbasis konten adalah...", "o": ["Hibrida", "Kolaboratif murni", "Konten murni", "Manual"], "a": 0},
    {"q": "Keterbatasan penyaringan kolaboratif adalah...", "o": ["Lemah pada pengguna atau produk baru tanpa riwayat", "Terlalu banyak menawarkan kebaruan", "Tidak butuh data", "Selalu akurat"], "a": 0},
    {"q": "Keterbatasan pendekatan berbasis konten adalah...", "o": ["Cenderung sempit dan kurang menawarkan kebaruan", "Terlalu acak", "Tidak butuh riwayat", "Selalu paling akurat"], "a": 0},
    {"q": "Keterbatasan pendekatan hibrida adalah...", "o": ["Lebih rumit dan menuntut lebih banyak sumber daya", "Selalu paling murah", "Tidak butuh data", "Tidak bisa akurat"], "a": 0},
    {"q": "Masalah awalan dingin (cold start) terjadi ketika...", "o": ["Sistem belum memiliki data tentang pengguna atau produk baru", "Server terlalu panas", "Data terlalu banyak", "Pelanggan sudah loyal"], "a": 0},
    {"q": "Cara mengatasi masalah awalan dingin adalah...", "o": ["Meminta preferensi awal atau menampilkan produk populer", "Menghapus pengguna baru", "Menutup pendaftaran", "Menaikkan harga"], "a": 0},
    {"q": "Personalisasi membentuk lingkaran kebaikan karena...", "o": ["Data lebih baik menghasilkan layanan lebih baik yang menghasilkan lebih banyak data", "Data selalu berkurang", "Layanan menurun terus", "Pelanggan menghilang"], "a": 0},
    {"q": "CLV (Customer Lifetime Value) menggambarkan...", "o": ["Total laba yang diharapkan dari seorang pelanggan selama berhubungan", "Biaya server bulanan", "Jumlah iklan", "Harga satu produk"], "a": 0},
    {"q": "Strategi omnichannel memastikan...", "o": ["Pengalaman konsisten dan mulus pada seluruh kanal", "Tiap kanal berjalan terpisah", "Data tidak disatukan", "Hanya satu kanal dipakai"], "a": 0},
    {"q": "Syarat utama omnichannel adalah...", "o": ["Konsistensi dan integrasi data lintas kanal", "Banyak logo berbeda", "Server terpisah tiap toko", "Harga berbeda tiap kanal"], "a": 0},
    {"q": "Perbedaan omnichannel dan multichannel adalah...", "o": ["Omnichannel menyatukan data sehingga pengalaman menyatu", "Keduanya identik", "Multichannel selalu lebih baik", "Omnichannel hanya untuk toko fisik"], "a": 0},
    {"q": "Risiko gelembung penyaring (filter bubble) adalah...", "o": ["Mengurung pelanggan dalam konten yang seragam", "Memperluas pilihan tanpa batas", "Menghapus rekomendasi", "Menurunkan konversi selalu"], "a": 0},
    {"q": "Chatbot dan asisten virtual berguna untuk...", "o": ["Melayani pertanyaan pelanggan sepanjang waktu dan meneruskan kasus rumit ke manusia", "Menggantikan seluruh manusia tanpa pengawasan", "Menaikkan harga", "Menghapus data"], "a": 0},
    {"q": "AI generatif dalam layanan pelanggan berperan...", "o": ["Menyusun pesan, deskripsi, dan tanggapan yang disesuaikan dalam skala besar", "Mematikan server", "Menghapus pelanggan", "Menaikkan biaya listrik"], "a": 0},
    {"q": "Analitik prediktif dapat memperkirakan...", "o": ["Kemungkinan pelanggan berhenti berlangganan (churn)", "Cuaca besok pasti", "Harga emas global", "Hasil pemilu"], "a": 0},
    {"q": "Segmentasi dinamis mengelompokkan pelanggan berdasarkan...", "o": ["Perilaku terkini, bukan kategori statis", "Abjad nama", "Nomor urut pendaftaran", "Warna favorit tetap"], "a": 0},
    {"q": "Metrik kunci pada tahap kesadaran dalam perjalanan pelanggan adalah...", "o": ["Jangkauan dan biaya per klik", "Tingkat retensi", "Nilai seumur hidup", "Skor kepuasan"], "a": 0},
    {"q": "Metrik kunci pada tahap pembelian adalah...", "o": ["Rasio konversi dan nilai pesanan", "Jangkauan", "Waktu kunjungan awal", "Biaya per klik"], "a": 0},
    {"q": "Metrik kunci pada tahap loyalitas adalah...", "o": ["Tingkat retensi dan nilai seumur hidup", "Biaya per klik", "Jangkauan", "Rasio klik iklan"], "a": 0},
    {"q": "Penerapan AI pada tahap pascapembelian umumnya berupa...", "o": ["Chatbot dan panduan otomatis", "Iklan tertarget awal", "Checkout cerdas", "Konten kesadaran merek"], "a": 0},
    {"q": "Personalisasi yang tepat meningkatkan...", "o": ["Konversi, nilai pesanan, dan loyalitas", "Biaya tanpa hasil", "Churn pelanggan", "Keluhan saja"], "a": 0},
    {"q": "Risiko pertukaran privasi dalam personalisasi adalah...", "o": ["Pengumpulan data berlebihan dapat melanggar privasi", "Data tidak pernah dibutuhkan", "Privasi tidak relevan", "Persetujuan tidak perlu"], "a": 0},
    {"q": "Kesan mengganggu (creepy) muncul ketika personalisasi...", "o": ["Terlalu jeli sehingga pelanggan merasa diawasi", "Terlalu umum", "Tidak akurat sama sekali", "Tidak menggunakan data"], "a": 0},
    {"q": "Personalisasi yang etis menempatkan...", "o": ["Kepentingan pelanggan di atas eksploitasi data", "Data di atas segalanya", "Iklan di atas pelayanan", "Harga di atas nilai"], "a": 0},
    {"q": "QS yang menekankan musyawarah dan kelembutan dalam interaksi pelanggan adalah...", "o": ["QS Ali Imran ayat 159", "QS Al-Hujurat ayat 12", "QS Al-Maidah ayat 2", "QS Al-A'raf ayat 85"], "a": 0},
    {"q": "Mesin rekomendasi disebut sebagai...", "o": ["Jantung personalisasi pada e-business", "Pengganti gudang", "Alat akuntansi", "Sistem pajak"], "a": 0},
    {"q": "Semakin banyak dan berkualitas data yang diolah, maka prediksi...", "o": ["Semakin akurat", "Semakin acak", "Semakin lambat selalu", "Tidak berubah"], "a": 0},
    {"q": "Perusahaan menjaga agar personalisasi terasa...", "o": ["Membantu, bukan menyeramkan", "Mengganggu", "Memaksa", "Menakutkan"], "a": 0},
    {"q": "Pengalaman lintas kanal berarti pelanggan berpindah antara...", "o": ["Situs web, aplikasi, media sosial, dan toko fisik dalam satu perjalanan", "Hanya satu aplikasi", "Hanya toko fisik", "Hanya email"], "a": 0},
    {"q": "Contoh konsistensi omnichannel adalah...", "o": ["Barang di keranjang aplikasi tetap ada saat membuka situs web", "Keranjang hilang tiap ganti perangkat", "Harga berbeda tiap kanal", "Login ulang tiap halaman"], "a": 0},
    {"q": "Metrik utama personalisasi mencakup...", "o": ["Rasio konversi, nilai pesanan, retensi, CAC, dan LTV", "Jumlah karyawan", "Luas kantor", "Warna logo"], "a": 0},
    {"q": "Personalisasi yang baik meningkatkan LTV dengan...", "o": ["Memperpanjang masa hubungan dan memperbesar belanja per pelanggan", "Mengurangi pelanggan", "Menaikkan churn", "Menghapus data"], "a": 0},
    {"q": "Platform streaming dan e-commerce besar memperoleh sebagian besar interaksi dari...", "o": ["Mesin rekomendasi", "Iklan cetak", "Surat pos", "Telepon manual"], "a": 0},
    {"q": "Pelajaran utama dari rekomendasi platform besar adalah...", "o": ["Personalisasi akurat meningkatkan keterlibatan dan pendapatan", "Personalisasi tidak berpengaruh", "Data merugikan bisnis", "Rekomendasi harus dihapus"], "a": 0},
    {"q": "Saat mengadopsi AI generatif untuk layanan, perusahaan tetap perlu...", "o": ["Menjaga pengawasan manusia atas jawaban sensitif", "Menghapus seluruh tim manusia", "Mematikan pengawasan", "Menonaktifkan chatbot"], "a": 0},
    {"q": "Segmentasi statis dianggap lemah karena...", "o": ["Kategori cepat usang", "Terlalu dinamis", "Terlalu akurat", "Tidak butuh data"], "a": 0},
    {"q": "Pemetaan perjalanan pelanggan membantu perusahaan...", "o": ["Mengidentifikasi titik gesekan dan peluang personalisasi", "Menaikkan harga acak", "Menghapus kanal", "Mengurangi pelanggan"], "a": 0},
    {"q": "Tahap pertimbangan pada perjalanan pelanggan memakai penerapan AI berupa...", "o": ["Rekomendasi produk dan ulasan terkurasi", "Program loyalitas", "Chatbot pascabeli", "Iklan kesadaran"], "a": 0},
    {"q": "CLV yang tinggi menandakan...", "o": ["Hubungan pelanggan bernilai dan tahan lama", "Pelanggan cepat pergi", "Biaya akuisisi mahal", "Produk gagal"], "a": 0},
    {"q": "Personalisasi berlebihan berpotensi berubah menjadi...", "o": ["Manipulasi atau pelanggaran privasi", "Layanan gratis", "Diskon otomatis", "Efisiensi murni"], "a": 0},
    {"q": "Checkout cerdas dan penawaran dinamis diterapkan pada tahap...", "o": ["Pembelian", "Kesadaran", "Loyalitas", "Pascapembelian"], "a": 0},
    {"q": "Pelanggan modern mengharapkan pengalaman yang...", "o": ["Relevan dengan kebutuhan mereka", "Seragam untuk semua", "Tanpa rekomendasi", "Selalu paling murah"], "a": 0},
    {"q": "AI generatif mampu menghasilkan konten pemasaran...", "o": ["Secara otomatis dan dalam skala besar", "Hanya satu per hari", "Tanpa konteks pelanggan", "Hanya manual"], "a": 0},
    {"q": "Kuis 2 pada Pertemuan 12 mencakup materi...", "o": ["Pertemuan 8 sampai 11", "Pertemuan 1 sampai 3", "Pertemuan 13 sampai 15", "Hanya Pertemuan 12"], "a": 0},
    {"q": "Sistem personalisasi belajar dari data perilaku seperti...", "o": ["Riwayat pencarian, pembelian, dan interaksi", "Golongan darah", "Warna mata", "Nomor rumah"], "a": 0},
    {"q": "Menyeimbangkan personalisasi dan privasi menuntut perusahaan...", "o": ["Meminta persetujuan yang sah", "Mengabaikan izin", "Menyembunyikan pengumpulan data", "Menjual data diam-diam"], "a": 0},
    {"q": "Program loyalitas personal dan retensi prediktif diterapkan pada tahap...", "o": ["Loyalitas", "Kesadaran", "Pertimbangan", "Pembelian"], "a": 0},

    # ---------- Pertemuan 13: Studi Kasus Keberhasilan dan Kegagalan (151-200) ----------
    {"q": "Efek jaringan terjadi ketika...", "o": ["Nilai layanan meningkat seiring bertambahnya pengguna", "Biaya server naik", "Pengguna berkurang", "Harga turun otomatis"], "a": 0},
    {"q": "Bias keselamatan (survivorship bias) adalah kecenderungan...", "o": ["Hanya mempelajari kisah sukses yang bertahan dan melupakan yang gagal", "Mempelajari semua kasus seimbang", "Menghindari kisah sukses", "Menolak data"], "a": 0},
    {"q": "Unit ekonomi yang buruk berarti...", "o": ["Setiap transaksi menambah kerugian karena biaya melebihi pendapatan", "Setiap transaksi untung besar", "Tidak ada transaksi", "Biaya selalu nol"], "a": 0},
    {"q": "Analisis PESTEL menelaah faktor...", "o": ["Politik, ekonomi, sosial, teknologi, lingkungan, hukum", "Produk, harga, tempat, promosi", "Kekuatan, kelemahan, peluang, ancaman", "Pemasok, pembeli, pesaing"], "a": 0},
    {"q": "Lima kekuatan Porter mencakup...", "o": ["Persaingan, pendatang baru, produk pengganti, daya tawar pemasok, daya tawar pembeli", "Politik, ekonomi, sosial, teknologi", "Kekuatan, kelemahan, peluang, ancaman", "Segmen, target, posisi"], "a": 0},
    {"q": "Analisis SWOT merangkum...", "o": ["Kekuatan, kelemahan, peluang, dan ancaman", "Politik dan hukum", "Pemasok dan pembeli", "Harga dan tempat"], "a": 0},
    {"q": "Amazon memperoleh sumber laba terbesar dari...", "o": ["Komputasi awan (layanan cloud)", "Penjualan buku cetak", "Iklan koran", "Sewa gudang saja"], "a": 0},
    {"q": "Shopify mengambil jalan berbeda dengan...", "o": ["Memberdayakan pedagang kecil membangun toko daring sendiri", "Bersaing langsung sebagai marketplace raksasa", "Menjual perangkat keras", "Membuka toko fisik global"], "a": 0},
    {"q": "Faktor keberhasilan e-business salah satunya...", "o": ["Memecahkan masalah nyata pelanggan dengan solusi lebih baik", "Membakar modal tanpa arah", "Mengabaikan data", "Menaikkan harga terus"], "a": 0},
    {"q": "Penyebab kegagalan e-business yang sering tersembunyi di balik pertumbuhan adalah...", "o": ["Unit ekonomi yang buruk", "Terlalu banyak laba", "Pelanggan terlalu loyal", "Modal berlebih"], "a": 0},
    {"q": "Efek jaringan membangun keunggulan berupa...", "o": ["Parit pertahanan yang sulit ditembus pesaing baru", "Kelemahan permanen", "Biaya tak terkendali", "Ketergantungan pemasok"], "a": 0},
    {"q": "Marketplace menjadi lebih berharga ketika...", "o": ["Lebih banyak penjual dan pembeli bergabung", "Pengguna berkurang", "Harga dinaikkan", "Fitur dikurangi"], "a": 0},
    {"q": "Pertumbuhan cepat sambil merugi tiap transaksi cenderung...", "o": ["Mempercepat kehancuran ketika modal habis", "Menjamin keberhasilan", "Menghapus risiko", "Menarik investor selamanya"], "a": 0},
    {"q": "Aspek proposisi nilai dalam kerangka analisis kasus menanyakan...", "o": ["Masalah apa yang dipecahkan dan bagi siapa", "Berapa jumlah karyawan", "Warna logo perusahaan", "Lokasi kantor pusat"], "a": 0},
    {"q": "Aspek keunggulan kompetitif menanyakan...", "o": ["Apa yang membedakan perusahaan dari pesaing", "Berapa gaji CEO", "Warna kemasan", "Jam operasional"], "a": 0},
    {"q": "Aspek unit ekonomi menanyakan...", "o": ["Apakah setiap transaksi menghasilkan margin yang sehat", "Berapa jumlah kantor", "Siapa pendiri", "Kapan didirikan"], "a": 0},
    {"q": "Kegagalan akibat ekspansi terlalu cepat mengajarkan pentingnya...", "o": ["Disiplin unit ekonomi, transparansi, dan pertumbuhan terukur", "Ekspansi tanpa batas", "Menyembunyikan data dari investor", "Mengabaikan tata kelola"], "a": 0},
    {"q": "Konteks Indonesia (Tokopedia, Bukalapak) memperlihatkan dinamika...", "o": ["Persaingan, konsolidasi lewat penggabungan, dan pencarian profitabilitas", "Kegagalan total seluruh pasar", "Ketiadaan regulasi", "Larangan e-commerce"], "a": 0},
    {"q": "QS yang menjadi dasar analisis multiperspektif adalah...", "o": ["QS Az-Zumar ayat 18", "QS Al-Hujurat ayat 12", "QS Al-Maidah ayat 2", "QS Al-A'raf ayat 85"], "a": 0},
    {"q": "Manfaat mempelajari kasus keberhasilan dan kegagalan adalah...", "o": ["Melatih berpikir kritis dan pengambilan keputusan strategis", "Menghafal nama perusahaan", "Menyalin logo", "Menghindari analisis"], "a": 0},
    {"q": "Perusahaan yang memanfaatkan data untuk keputusan cenderung...", "o": ["Memperbaiki produk secara berkelanjutan", "Kehilangan arah", "Mengabaikan pelanggan", "Menaikkan biaya tanpa hasil"], "a": 0},
    {"q": "Salah membaca kebutuhan pasar menyebabkan...", "o": ["Memaksakan produk yang tidak dibutuhkan", "Kesuksesan pasti", "Pertumbuhan otomatis", "Loyalitas tinggi"], "a": 0},
    {"q": "Membakar modal tanpa jalur menuju profitabilitas adalah...", "o": ["Penyebab kegagalan e-business", "Strategi terbaik", "Jaminan keberhasilan", "Prinsip lean startup"], "a": 0},
    {"q": "Model platform Amazon dan Shopify sama-sama menunjukkan...", "o": ["Kekuatan memberi nilai bagi banyak pihak", "Kegagalan model platform", "Pentingnya toko fisik saja", "Ketidakgunaan data"], "a": 0},
    {"q": "Faktor lokal yang memengaruhi strategi di Indonesia mencakup...", "o": ["Perilaku konsumen, infrastruktur logistik, dan regulasi", "Cuaca Eropa", "Kurs dolar saja", "Warna bendera"], "a": 0},
    {"q": "Menjaga kepercayaan lewat tata kelola dan keamanan penting agar perusahaan...", "o": ["Tidak gagal akibat hilangnya kepercayaan", "Boleh mengabaikan pelanggan", "Bebas dari regulasi", "Tidak perlu audit"], "a": 0},
    {"q": "Beradaptasi cepat terhadap perubahan pasar merupakan...", "o": ["Faktor keberhasilan e-business", "Penyebab kegagalan", "Hal yang tidak penting", "Larangan regulasi"], "a": 0},
    {"q": "Analisis kasus sebaiknya menelaah kisah sukses dan gagal secara...", "o": ["Seimbang agar kesimpulan tidak menyesatkan", "Sepihak", "Hanya sukses", "Hanya gagal"], "a": 0},
    {"q": "Aspek model bisnis dalam kerangka analisis menanyakan...", "o": ["Bagaimana perusahaan menghasilkan dan menangkap nilai", "Warna seragam", "Jumlah cabang", "Nama pendiri"], "a": 0},
    {"q": "Aspek faktor penentu menanyakan...", "o": ["Keputusan apa yang menentukan keberhasilan atau kegagalan", "Menu kantin", "Warna logo", "Jam istirahat"], "a": 0},
    {"q": "Aspek pelajaran dalam kerangka analisis menanyakan...", "o": ["Apa yang dapat dipelajari dan diterapkan pada konteks lain", "Berapa lift di kantor", "Merek mobil CEO", "Jenis kopi favorit"], "a": 0},
    {"q": "Startup bernilai tinggi bisa runtuh terutama karena...", "o": ["Memperluas usaha tanpa fondasi keuangan dan tata kelola yang sehat", "Terlalu hemat", "Terlalu banyak audit", "Pertumbuhan terlalu lambat"], "a": 0},
    {"q": "Membangun model bisnis yang menghasilkan arus kas berkelanjutan adalah...", "o": ["Faktor keberhasilan", "Penyebab kegagalan", "Hal sepele", "Larangan"], "a": 0},
    {"q": "Gagal bersaing melawan pemain lebih besar dan efisien merupakan...", "o": ["Penyebab kegagalan e-business", "Jaminan sukses", "Strategi lean", "Efek jaringan"], "a": 0},
    {"q": "Alat analisis klasik yang menelaah persaingan industri adalah...", "o": ["Lima kekuatan Porter", "SWOT", "PESTEL", "BCG matrix"], "a": 0},
    {"q": "Alat analisis yang menelaah faktor makro eksternal adalah...", "o": ["PESTEL", "Lima kekuatan Porter", "SWOT internal", "Lean Canvas"], "a": 0},
    {"q": "Pertumbuhan yang mengesankan bisa menutupi...", "o": ["Unit ekonomi yang tidak sehat", "Laba berlebih", "Kepercayaan tinggi", "Efisiensi sempurna"], "a": 0},
    {"q": "Ekosistem terintegrasi Amazon mencakup...", "o": ["Marketplace, logistik, dan komputasi awan", "Hanya toko buku", "Hanya iklan", "Hanya gudang"], "a": 0},
    {"q": "Menganalisis kasus dengan kerangka sistematis memastikan analisis menyentuh...", "o": ["Strategi, operasi, keuangan, dan konteks pasar", "Hanya keuangan", "Hanya pemasaran", "Hanya logo"], "a": 0},
    {"q": "Menimbang beragam sudut pandang sebelum menyimpulkan sejalan dengan nilai...", "o": ["Fathonah (kecerdasan dan kebijaksanaan)", "Riya", "Takabur", "Gharar"], "a": 0},
    {"q": "Perusahaan yang menjaga pengalaman pelanggan cenderung membangun...", "o": ["Loyalitas", "Churn", "Kegagalan", "Kerugian"], "a": 0},
    {"q": "Daya tawar pemasok dan pembeli dianalisis dalam kerangka...", "o": ["Lima kekuatan Porter", "PESTEL", "Triple bottom line", "Triad CIA"], "a": 0},
    {"q": "Belajar dari pemenang dan pecundang pasar bertujuan memahami...", "o": ["Faktor penentu keberhasilan dan jebakan kegagalan", "Cara menyalin logo", "Harga saham harian", "Warna kemasan"], "a": 0},
    {"q": "Efek jaringan menjadi parit pertahanan karena...", "o": ["Sulit ditiru pesaing seiring pertumbuhan pengguna", "Mudah disalin", "Tidak berharga", "Menurunkan nilai"], "a": 0},
    {"q": "Tokopedia dan Bukalapak menghadapi tantangan utama berupa...", "o": ["Pencarian profitabilitas di pasar kompetitif", "Ketiadaan pengguna", "Larangan beroperasi", "Tidak ada pesaing"], "a": 0},
    {"q": "Kerangka analisis kasus melengkapi enam aspek dengan...", "o": ["Alat klasik seperti PESTEL, Porter, dan SWOT", "Warna dan font", "Menu kantin", "Jadwal libur"], "a": 0},
    {"q": "Pelajaran dari kasus menjadi bekal untuk...", "o": ["Merancang rencana bisnis pada pertemuan berikutnya", "Menghentikan analisis", "Menghindari strategi", "Menyalin pesaing persis"], "a": 0},
    {"q": "Disiplin pada unit ekonomi berarti memastikan...", "o": ["Setiap transaksi memberi kontribusi positif", "Setiap transaksi rugi", "Tidak ada transaksi", "Biaya diabaikan"], "a": 0},
    {"q": "Transparansi kepada investor penting untuk...", "o": ["Menjaga kepercayaan dan tata kelola yang sehat", "Menyembunyikan kerugian", "Menaikkan valuasi palsu", "Menghindari audit"], "a": 0},
    {"q": "Analisis multiperspektif menuntut mahasiswa...", "o": ["Menimbang beragam sudut pandang dan bukti sebelum menyimpulkan", "Mengikuti satu opini saja", "Menolak data", "Menyalin kesimpulan orang lain"], "a": 0},

    # ---------- Pertemuan 14: Perancangan Rencana Bisnis Digital (201-250) ----------
    {"q": "Rencana bisnis digital berfungsi menerjemahkan gagasan menjadi...", "o": ["Peta jalan yang dapat dieksekusi", "Iklan tunggal", "Logo perusahaan", "Daftar harga"], "a": 0},
    {"q": "Siklus inti pendekatan lean startup adalah...", "o": ["Bangun, ukur, belajar", "Beli, jual, untung", "Rencana, doa, tunggu", "Iklan, promosi, diskon"], "a": 0},
    {"q": "Produk minimum yang layak (MVP) adalah...", "o": ["Versi paling sederhana yang sudah memberi nilai dan mengundang umpan balik", "Produk final tanpa cela", "Prototipe yang tidak berfungsi", "Iklan produk"], "a": 0},
    {"q": "TAM (Total Addressable Market) berarti...", "o": ["Total permintaan jika seluruh pasar dapat diraih", "Pasar yang sudah direbut", "Bagian realistis jangka pendek", "Jumlah pesaing"], "a": 0},
    {"q": "SAM (Serviceable Available Market) berarti...", "o": ["Bagian pasar yang sesuai model bisnis dan jangkauan", "Seluruh populasi dunia", "Pasar yang sudah dikuasai penuh", "Jumlah karyawan"], "a": 0},
    {"q": "SOM (Serviceable Obtainable Market) berarti...", "o": ["Bagian realistis yang dapat direbut dalam jangka pendek", "Total pasar global", "Pasar pesaing", "Seluruh permintaan teoretis"], "a": 0},
    {"q": "CAC (Customer Acquisition Cost) adalah...", "o": ["Biaya rata-rata memperoleh satu pelanggan baru", "Laba per pelanggan", "Harga produk", "Biaya server"], "a": 0},
    {"q": "LTV (Lifetime Value) adalah...", "o": ["Total laba yang diharapkan dari satu pelanggan", "Biaya iklan bulanan", "Harga satu produk", "Jumlah pelanggan"], "a": 0},
    {"q": "Rasio LTV terhadap CAC yang dianggap sehat umumnya...", "o": ["Tiga banding satu atau lebih", "Satu banding tiga", "Nol banding satu", "Sepuluh banding sepuluh"], "a": 0},
    {"q": "Titik impas (break even point) tercapai saat...", "o": ["Pendapatan menutup seluruh biaya", "Laba maksimal", "Biaya nol", "Penjualan pertama terjadi"], "a": 0},
    {"q": "Margin kontribusi dihitung dari...", "o": ["Pendapatan dikurangi biaya variabel per transaksi", "Pendapatan ditambah biaya", "Modal dikurangi utang", "Harga dikali jumlah unit"], "a": 0},
    {"q": "Waktu pengembalian (payback period) menunjukkan...", "o": ["Lama waktu hingga CAC tertutup oleh pendapatan", "Umur perusahaan", "Lama pengiriman", "Durasi iklan"], "a": 0},
    {"q": "Business Model Canvas terdiri dari...", "o": ["Sembilan blok", "Empat blok", "Dua belas blok", "Tiga blok"], "a": 0},
    {"q": "Lean Canvas menyesuaikan kerangka kanvas untuk usaha rintisan dengan menekankan...", "o": ["Masalah, solusi, metrik kunci, dan keunggulan sulit ditiru", "Warna dan font", "Jumlah karyawan", "Lokasi kantor"], "a": 0},
    {"q": "Blok 'proposisi nilai' pada BMC menjawab pertanyaan...", "o": ["Nilai apa yang ditawarkan dan mengapa unik", "Siapa pemasok", "Berapa biaya sewa", "Kapan berdiri"], "a": 0},
    {"q": "Blok 'segmen pelanggan' pada BMC menjawab...", "o": ["Siapa pelanggan yang dilayani", "Berapa laba", "Apa warna logo", "Siapa CEO"], "a": 0},
    {"q": "Blok 'arus pendapatan' pada BMC menjawab...", "o": ["Dari mana pendapatan berasal", "Siapa pesaing", "Berapa karyawan", "Di mana kantor"], "a": 0},
    {"q": "Blok 'struktur biaya' pada BMC menjawab...", "o": ["Apa komponen biaya utama", "Siapa pelanggan", "Apa nilai unik", "Siapa mitra"], "a": 0},
    {"q": "Sebelum menyusun proyeksi keuangan, tim memastikan...", "o": ["Unit ekonomi yang sehat", "Iklan termahal", "Kantor termewah", "Logo terbaik"], "a": 0},
    {"q": "Investor menilai kelayakan bisnis terutama melalui...", "o": ["Kualitas asumsi dan kewajaran proyeksi", "Warna presentasi", "Jumlah slide", "Merek laptop tim"], "a": 0},
    {"q": "Konsep landasan kas (cash runway) menunjukkan...", "o": ["Berapa lama bisnis bertahan dengan kas sebelum butuh pendanaan tambahan", "Panjang landasan bandara", "Jumlah pelanggan", "Harga saham"], "a": 0},
    {"q": "Validasi pasar dilakukan tim dengan...", "o": ["Berbicara dengan calon pelanggan, membuat purwarupa, dan uji coba kecil", "Langsung membangun produk penuh", "Mengabaikan pelanggan", "Menaikkan harga dulu"], "a": 0},
    {"q": "MVP mencegah tim...", "o": ["Membangun sesuatu yang ternyata tidak dibutuhkan pasar", "Mendapat umpan balik", "Menghemat sumber daya", "Menguji asumsi"], "a": 0},
    {"q": "QS yang menjadi dasar kerja tim dalam proyek (tolong-menolong dalam kebaikan) adalah...", "o": ["QS Al-Maidah ayat 2", "QS Al-Hujurat ayat 12", "QS Az-Zumar ayat 18", "QS Al-A'raf ayat 85"], "a": 0},
    {"q": "Ringkasan eksekutif dalam rencana bisnis sebaiknya...", "o": ["Menyajikan inti rencana secara ringkas dan menarik dalam satu halaman", "Sepanjang 50 halaman", "Berisi hanya angka", "Tanpa proposisi nilai"], "a": 0},
    {"q": "Komponen 'masalah dan solusi' dalam rencana bisnis menjelaskan...", "o": ["Masalah pelanggan yang nyata dan solusi yang ditawarkan", "Warna kemasan", "Jadwal libur", "Merek kendaraan"], "a": 0},
    {"q": "Komponen 'model pendapatan' menjelaskan...", "o": ["Cara bisnis menghasilkan uang secara berkelanjutan", "Warna logo", "Jumlah rapat", "Lokasi gudang"], "a": 0},
    {"q": "Pendekatan lean startup menyarankan tim untuk...", "o": ["Menguji asumsi paling berisiko sedini mungkin", "Menyusun rencana sempurna di atas kertas dulu", "Mengabaikan pasar", "Menghindari pengukuran"], "a": 0},
    {"q": "Tim mengukur pasar melalui tiga lapis (TAM, SAM, SOM) agar estimasi...", "o": ["Realistis dan dapat dipertahankan di hadapan investor", "Terlihat besar tanpa dasar", "Tidak perlu bukti", "Selalu maksimal"], "a": 0},
    {"q": "Pemetaan kompetitor mencakup...", "o": ["Pesaing langsung, tidak langsung, dan alternatif pelanggan saat ini", "Hanya pesaing terbesar", "Hanya diri sendiri", "Tidak ada pesaing"], "a": 0},
    {"q": "Rasio LTV:CAC 3:1 menandakan...", "o": ["Unit ekonomi yang sehat", "Bisnis merugi", "Biaya akuisisi terlalu murah untuk dihitung", "Tidak ada pelanggan"], "a": 0},
    {"q": "Proyeksi keuangan menerjemahkan strategi menjadi...", "o": ["Angka", "Warna", "Slogan", "Logo"], "a": 0},
    {"q": "Tim memproyeksikan arus kas biasanya untuk...", "o": ["Dua belas bulan pertama", "Seratus tahun", "Satu hari", "Tidak sama sekali"], "a": 0},
    {"q": "Komponen 'tim dan eksekusi' menjelaskan...", "o": ["Peran anggota, tonggak pencapaian, dan mitigasi risiko", "Warna seragam", "Menu makan siang", "Merek laptop"], "a": 0},
    {"q": "Blok 'saluran' pada BMC menjawab...", "o": ["Bagaimana produk menjangkau pelanggan", "Berapa laba bersih", "Siapa investor", "Kapan berdiri"], "a": 0},
    {"q": "Blok 'kemitraan kunci' pada BMC menjawab...", "o": ["Siapa mitra strategis yang dibutuhkan", "Apa warna logo", "Berapa gaji CEO", "Di mana kantor pusat"], "a": 0},
    {"q": "Blok 'sumber daya kunci' pada BMC menjawab...", "o": ["Aset apa yang diperlukan", "Siapa pelanggan", "Apa harga jual", "Kapan promosi"], "a": 0},
    {"q": "Blok 'aktivitas kunci' pada BMC menjawab...", "o": ["Kegiatan inti apa yang dijalankan", "Warna kemasan", "Nama pendiri", "Jam kerja"], "a": 0},
    {"q": "Blok 'hubungan pelanggan' pada BMC menjawab...", "o": ["Bagaimana hubungan dibangun dan dijaga", "Berapa biaya listrik", "Siapa pemasok", "Kapan libur"], "a": 0},
    {"q": "Rencana bisnis digital merupakan puncak penerapan materi...", "o": ["Sepanjang semester, dari model bisnis hingga keamanan dan keberlanjutan", "Hanya satu pertemuan", "Hanya soal logo", "Hanya iklan"], "a": 0},
    {"q": "Purwarupa (prototype) dibuat tim untuk...", "o": ["Menguji asumsi sebelum membangun produk penuh", "Menggantikan produk final selamanya", "Menaikkan harga", "Menghindari pelanggan"], "a": 0},
    {"q": "Analisis pasar bertujuan memastikan...", "o": ["Terdapat permintaan yang cukup terhadap solusi", "Pesaing tidak ada", "Harga selalu naik", "Modal tak terbatas"], "a": 0},
    {"q": "Estimasi SOM penting agar tim...", "o": ["Menetapkan target yang realistis untuk jangka pendek", "Menargetkan seluruh dunia sekaligus", "Mengabaikan pasar", "Menghindari investor"], "a": 0},
    {"q": "Proyeksi pendapatan disusun berdasarkan asumsi...", "o": ["Jumlah pelanggan dan harga", "Warna logo", "Cuaca", "Nomor keberuntungan"], "a": 0},
    {"q": "Nilai LTV yang jauh lebih besar dari CAC menandakan...", "o": ["Bisnis berpotensi menguntungkan dan berkelanjutan", "Bisnis pasti gagal", "Pelanggan tidak berharga", "Biaya akuisisi terlalu tinggi"], "a": 0},
    {"q": "Titik impas membantu tim mengetahui...", "o": ["Tingkat penjualan minimum agar tidak merugi", "Warna kemasan ideal", "Jumlah rapat", "Merek kendaraan"], "a": 0},
    {"q": "Kerja tim yang jujur dan saling melengkapi keahlian mencerminkan nilai profetik...", "o": ["Amanah dan ta'awun (tolong-menolong)", "Takabur", "Riya", "Israf"], "a": 0},
    {"q": "Rencana yang matang dan teruji menjadi bekal untuk...", "o": ["Presentasi (pitching) pada pertemuan terakhir", "Menutup usaha", "Menghindari investor", "Membakar modal"], "a": 0},
    {"q": "Siklus bangun, ukur, belajar bertujuan...", "o": ["Menghemat sumber daya dan menurunkan risiko kegagalan", "Memperbesar risiko", "Menghabiskan modal cepat", "Menghindari pengukuran"], "a": 0},
    {"q": "Komponen 'proyeksi keuangan' dalam rencana bisnis menyusun...", "o": ["Perkiraan pendapatan, biaya, dan titik impas", "Daftar libur nasional", "Warna presentasi", "Playlist musik"], "a": 0},
]

# Sanity check jumlah soal saat modul diimpor
assert len(UAS_BANK) == 250, f"Bank soal UAS harus 250, saat ini {len(UAS_BANK)}"
